package server

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

const importMarker = "preview-managed-import"

// WriteAtomic replaces path with data, using a temporary file in the same directory.
func WriteAtomic(path string, data []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".preview-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

// InstallSnippet writes the managed Caddy site. Files not created by preview are left alone unless force is set.
func InstallSnippet(path, content string, force bool) error {
	existing, err := os.ReadFile(path)
	if err == nil && !bytes.Contains(existing, []byte(generatedMarker)) && !force {
		return fmt.Errorf("%s already exists and was not generated by preview; move it aside or rerun with --force", path)
	} else if err != nil && !os.IsNotExist(err) {
		return err
	}
	return WriteAtomic(path, []byte(content), 0o644)
}

// EnsureImport appends an import for snippetPath when the main Caddyfile does not already have one.
// A missing main file is created with a localhost admin endpoint.
func EnsureImport(mainPath, snippetPath, adminURL, email string) (bool, error) {
	data, err := os.ReadFile(mainPath)
	if os.IsNotExist(err) {
		content, err := RenderMain(adminURL, email, snippetPath)
		if err != nil {
			return false, err
		}
		return true, WriteAtomic(mainPath, []byte(content), 0o644)
	}
	if err != nil {
		return false, err
	}
	if hasImport(string(data), snippetPath) {
		return false, nil
	}
	extra := fmt.Sprintf("\n# %s\nimport %s\n", importMarker, snippetPath)
	return true, WriteAtomic(mainPath, append(data, []byte(extra)...), 0o644)
}

func hasImport(content, snippetPath string) bool {
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == "import" && fields[1] == snippetPath {
			return true
		}
	}
	return false
}

// CheckDNSModule reports whether the Caddy binary includes the provider module.
func CheckDNSModule(bin, provider string) error {
	if strings.TrimSpace(bin) == "" {
		bin = "caddy"
	}
	if _, err := exec.LookPath(bin); err != nil && !filepath.IsAbs(bin) {
		return fmt.Errorf("caddy binary %q was not found on PATH\n\nInstall Caddy with the %s DNS module:\n  xcaddy build --with %s\n\nOr download a custom build from https://caddyserver.com/download", bin, provider, ModulePackage(provider))
	}
	cmd := exec.Command(bin, "list-modules")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s list-modules failed: %w\n%s", bin, err, strings.TrimSpace(string(out)))
	}
	module := ModuleID(provider)
	if !bytes.Contains(out, []byte(module)) {
		return fmt.Errorf("caddy is missing %s\n\nBuild a compatible binary:\n  xcaddy build --with %s\n\nOr download one from https://caddyserver.com/download with the %s DNS provider selected", module, ModulePackage(provider), provider)
	}
	return nil
}

// Validate asks Caddy to parse the main configuration.
func Validate(bin, mainPath, dnsEnvPath, envName string) error {
	cmd := exec.Command(bin, "validate", "--config", mainPath, "--adapter", "caddyfile")
	cmd.Env = commandEnv(dnsEnvPath, envName)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy validate failed: %w\n%s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// Restart starts Caddy again so it picks up unit changes such as a new DNS token.
func Restart(bin, mainPath, dnsEnvPath, envName string) error {
	if _, err := exec.LookPath("systemctl"); err == nil {
		cmd := exec.Command("systemctl", "restart", "caddy")
		out, err := cmd.CombinedOutput()
		if err == nil {
			return nil
		}
		text := strings.ToLower(string(out))
		if !strings.Contains(text, "not found") && !strings.Contains(text, "could not be found") {
			return fmt.Errorf("systemctl restart caddy: %w\n%s", err, strings.TrimSpace(string(out)))
		}
	}
	return reloadDirect(bin, mainPath, dnsEnvPath, envName)
}

// Reload applies the Caddyfile to the running server.
func Reload(bin, mainPath, dnsEnvPath, envName string) error {
	if _, err := exec.LookPath("systemctl"); err == nil {
		if exec.Command("systemctl", "is-active", "--quiet", "caddy").Run() == nil {
			cmd := exec.Command("systemctl", "reload", "caddy")
			out, err := cmd.CombinedOutput()
			if err == nil {
				return nil
			}
			reloadErr := fmt.Errorf("systemctl reload caddy: %w\n%s", err, strings.TrimSpace(string(out)))
			direct := reloadDirect(bin, mainPath, dnsEnvPath, envName)
			if direct == nil {
				return nil
			}
			return fmt.Errorf("%v\n%v", reloadErr, direct)
		}
		cmd := exec.Command("systemctl", "enable", "--now", "caddy")
		out, err := cmd.CombinedOutput()
		if err == nil {
			return nil
		}
		if direct := reloadDirect(bin, mainPath, dnsEnvPath, envName); direct == nil {
			return nil
		}
		return fmt.Errorf("systemctl enable --now caddy: %w\n%s", err, strings.TrimSpace(string(out)))
	}
	return reloadDirect(bin, mainPath, dnsEnvPath, envName)
}

func reloadDirect(bin, mainPath, dnsEnvPath, envName string) error {
	cmd := exec.Command(bin, "reload", "--config", mainPath, "--adapter", "caddyfile")
	cmd.Env = commandEnv(dnsEnvPath, envName)
	out, err := cmd.CombinedOutput()
	if err != nil {
		start := exec.Command(bin, "start", "--config", mainPath, "--adapter", "caddyfile")
		start.Env = cmd.Env
		startOut, startErr := start.CombinedOutput()
		if startErr == nil {
			return nil
		}
		return fmt.Errorf("caddy reload: %w\n%s\ncaddy start: %v\n%s", err, strings.TrimSpace(string(out)), startErr, strings.TrimSpace(string(startOut)))
	}
	return nil
}

func commandEnv(dnsEnvPath, envName string) []string {
	merged := map[string]string{}
	order := make([]string, 0)
	add := func(key, value string) {
		if _, ok := merged[key]; !ok {
			order = append(order, key)
		}
		merged[key] = value
	}
	for _, item := range os.Environ() {
		key, value, ok := strings.Cut(item, "=")
		if !ok || key == "" {
			continue
		}
		add(key, value)
	}
	for key, value := range ParseEnvFile(dnsEnvPath) {
		if strings.TrimSpace(value) == "" {
			continue
		}
		add(key, value)
	}
	if envName != "" && strings.TrimSpace(merged[envName]) == "" {
		add(envName, "preview-validate-placeholder")
	}
	env := make([]string, 0, len(order))
	for _, key := range order {
		env = append(env, key+"="+merged[key])
	}
	return env
}

// ParseEnvFile reads KEY=VALUE lines. Missing files return an empty map.
func ParseEnvFile(path string) map[string]string {
	data, err := os.ReadFile(path)
	if err != nil {
		return map[string]string{}
	}
	out := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = strings.TrimPrefix(line, "export ")
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		value = strings.Trim(strings.TrimSpace(value), `"'`)
		if key != "" {
			out[key] = value
		}
	}
	return out
}

// EnvFileHasValue reports whether path sets key to a non-empty value.
func EnvFileHasValue(path, key string) bool {
	return strings.TrimSpace(ParseEnvFile(path)[key]) != ""
}

// DNSEnvPath is the secrets file that sits next to the config file.
func DNSEnvPath(configPath string) string {
	return filepath.Join(filepath.Dir(configPath), "dns.env")
}

// WriteDNSEnv creates or updates the DNS credential file. An empty token does not erase an existing value.
func WriteDNSEnv(path, key, token string) error {
	if strings.TrimSpace(key) == "" {
		return fmt.Errorf("dns credential environment variable name is empty")
	}
	existing := ParseEnvFile(path)
	if strings.TrimSpace(token) == "" {
		if existing[key] != "" || fileExists(path) {
			return nil
		}
		token = ""
	}
	if strings.TrimSpace(token) != "" {
		existing[key] = token
	} else if _, ok := existing[key]; !ok {
		existing[key] = ""
	}
	var b strings.Builder
	b.WriteString("# DNS credentials for Caddy wildcard certificates. Keep this file private.\n")
	fmt.Fprintf(&b, "%s=%s\n", key, existing[key])
	return WriteAtomic(path, []byte(b.String()), 0o600)
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// AdoptSudoUser gives the invoking sudo user ownership of paths so later preview commands work without root.
func AdoptSudoUser(paths ...string) {
	uidText := os.Getenv("SUDO_UID")
	gidText := os.Getenv("SUDO_GID")
	if uidText == "" {
		return
	}
	uid, err1 := strconv.Atoi(uidText)
	gid, err2 := strconv.Atoi(gidText)
	if err1 != nil || err2 != nil || uid == 0 {
		return
	}
	for _, path := range paths {
		_ = os.Chown(path, uid, gid)
	}
}
