package server

import (
	"fmt"
	"strings"

	"github.com/harshalranjhani/preview-cli/internal/config"
)

const generatedMarker = "GENERATED BY preview"

// RenderSnippet builds the Caddy site block preview owns.
func RenderSnippet(cfg config.Config, configPath string) (string, error) {
	if err := cfg.Validate(); err != nil {
		return "", err
	}
	if configPath == "" {
		configPath = config.DefaultPath
	}
	var b strings.Builder
	b.WriteString("# " + generatedMarker + " — DO NOT EDIT MANUALLY.\n")
	fmt.Fprintf(&b, "# Change %s and run:\n", configPath)
	b.WriteString("#   sudo preview server apply\n\n")
	fmt.Fprintf(&b, "*.%s {\n", cfg.Server.BaseDomain)
	b.WriteString(tlsBlock(cfg))
	b.WriteString("\thandle {\n")
	b.WriteString("\t\trespond \"no preview configured for this host\" 404\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func tlsBlock(cfg config.Config) string {
	provider := strings.ToLower(strings.TrimSpace(cfg.DNS.Provider))
	if provider == "route53" {
		return "\ttls {\n\t\tdns route53\n\t}\n\n"
	}
	return fmt.Sprintf("\ttls {\n\t\tdns %s {env.%s}\n\t}\n\n", provider, cfg.DNS.CredentialsEnv)
}

// RenderMain builds a new top-level Caddyfile that imports the managed site.
func RenderMain(adminURL, email, snippetPath string) (string, error) {
	listen, err := config.AdminListen(adminURL)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("{\n")
	fmt.Fprintf(&b, "\tadmin %s\n", listen)
	if strings.TrimSpace(email) != "" {
		fmt.Fprintf(&b, "\temail %s\n", email)
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "# %s\nimport %s\n", importMarker, snippetPath)
	return b.String(), nil
}

// ModuleID is the Caddy module name for a DNS provider.
func ModuleID(provider string) string {
	provider = strings.ToLower(strings.TrimSpace(provider))
	return "dns.providers." + provider
}

// ModulePackage is the xcaddy package for a DNS provider.
func ModulePackage(provider string) string {
	return "github.com/caddy-dns/" + strings.ToLower(strings.TrimSpace(provider))
}
