package server

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/harshalranjhani/preview-cli/internal/config"
)

func testConfig() config.Config {
	cfg := config.Default()
	cfg.Server.BaseDomain = "preview.example.com"
	cfg.Server.PublicIP = "203.0.113.10"
	cfg.Server.ACMEEmail = "ops@example.com"
	cfg.ApplyDefaults()
	return cfg
}

func TestRenderSnippet(t *testing.T) {
	snippet, err := RenderSnippet(testConfig(), "/etc/preview/config.yaml")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"GENERATED BY preview",
		"*.preview.example.com",
		"dns cloudflare {env.CLOUDFLARE_API_TOKEN}",
		"no preview configured for this host",
		"/etc/preview/config.yaml",
	} {
		if !strings.Contains(snippet, want) {
			t.Fatalf("snippet missing %q\n%s", want, snippet)
		}
	}
	if strings.Contains(snippet, "api_token_value") {
		t.Fatal("snippet should not contain a token")
	}
}

func TestEnsureImportIsIdempotent(t *testing.T) {
	dir := t.TempDir()
	mainPath := filepath.Join(dir, "Caddyfile")
	snippet := filepath.Join(dir, "preview.caddy")
	changed, err := EnsureImport(mainPath, snippet, "http://127.0.0.1:2019", "ops@example.com")
	if err != nil || !changed {
		t.Fatalf("changed %v err %v", changed, err)
	}
	body, err := os.ReadFile(mainPath)
	if err != nil {
		t.Fatal(err)
	}
	text := string(body)
	if !strings.Contains(text, "admin 127.0.0.1:2019") || !strings.Contains(text, "email ops@example.com") {
		t.Fatalf("main file:\n%s", text)
	}
	if !strings.Contains(text, "import "+snippet) {
		t.Fatal(text)
	}
	changed, err = EnsureImport(mainPath, snippet, "http://127.0.0.1:2019", "ops@example.com")
	if err != nil || changed {
		t.Fatalf("second changed %v err %v", changed, err)
	}
}

func TestEnsureImportKeepsExistingSites(t *testing.T) {
	dir := t.TempDir()
	mainPath := filepath.Join(dir, "Caddyfile")
	original := "example.com {\n\trespond \"ok\"\n}\n"
	if err := os.WriteFile(mainPath, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}
	snippet := filepath.Join(dir, "preview.caddy")
	if _, err := EnsureImport(mainPath, snippet, "http://127.0.0.1:2019", ""); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(mainPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(body), original) || !strings.Contains(string(body), "import "+snippet) {
		t.Fatalf("existing site was rewritten:\n%s", body)
	}
}

func TestInstallSnippetRefusesForeignFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "preview.caddy")
	if err := os.WriteFile(path, []byte("example.com {\n}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := InstallSnippet(path, "# GENERATED BY preview\n", false); err == nil {
		t.Fatal("expected refusal")
	}
	if err := InstallSnippet(path, "# GENERATED BY preview\n", true); err != nil {
		t.Fatal(err)
	}
}

func TestCommandEnvIgnoresEmptyToken(t *testing.T) {
	path := filepath.Join(t.TempDir(), "dns.env")
	if err := os.WriteFile(path, []byte("CLOUDFLARE_API_TOKEN=\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("CLOUDFLARE_API_TOKEN", "")
	env := commandEnv(path, "CLOUDFLARE_API_TOKEN")
	found := ""
	for _, item := range env {
		if strings.HasPrefix(item, "CLOUDFLARE_API_TOKEN=") {
			found = item
		}
	}
	if found != "CLOUDFLARE_API_TOKEN=preview-validate-placeholder" {
		t.Fatalf("env value %q", found)
	}
}
